Section 30
Oswaldo-Chan/curso-desarrollo-web pull request #26
Opened 2023-05-13 02:37 UTC by Oswaldo-Chan

me faltan 4 videos para terminar la seccion 30

2023-05-13 23:57 UTC, CheloChidoone commented on bienes-raices/admin/index.php
> +                                <a class="btn-green-block" href="admin/properties/update.php?id=<?php echo $property['id'] ?>">Actualizar</a>
Tienes un error aqui que hace que no funcione tu boton de "Actualizar" en tus propiedades, recuerda que aqui ya estas en la carpeta admin y aqui pusiste la ruta relativa poniendo "admin/..." eso hace que crea que tu archivo update.php este dentro de dos carpetas admin "admin/admin/..." y obviamente esto falla

2023-05-14 00:04 UTC, CheloChidoone requested changes
@Oswaldo-Chan Buen avance pero tienes unos errores, te deje un comentario del primero que es en tu admin una ruta que no funciona bien y el otro tambien son unas rutas ya que en tus paginas principales de blog y anuncios tienes rutas que apuntan a archivos .html y debes cambiarlas a que apunten a los archivos que ahora son .php, haz esos cambios por favor

2023-05-14 04:54 UTC, Oswaldo-Chan commented on bienes-raices/admin/index.php
> +                                <a class="btn-green-block" href="admin/properties/update.php?id=<?php echo $property['id'] ?>">Actualizar</a>
Hola, si te está fallando? es que volvi a checar el video y asi lo tenía el maestro, sin embargo siento que tienes razón pero al poner el href como "properties/update.php" no funciona y la url queda como localhost:3000/properties/update.php, pero con una ruta relativa si funciona, sería de la siguiente forma: "./properties/update.php"

2023-05-14 05:01 UTC, Oswaldo-Chan commented on bienes-raices/admin/index.php
> +                                <a class="btn-green-block" href="admin/properties/update.php?id=<?php echo $property['id'] ?>">Actualizar</a>
tomé en cuenta también lo que hice en la parte de crear una nueva propiedad y ahí le agregue un / al principio indicando que primero empezará desde la raíz del proyecto y ahí buscará una carpeta admin. ahorita subo ese cambio

2023-05-14 09:25 UTC, closed without merging