Section 32
Oswaldo-Chan/curso-desarrollo-web pull request #29
Opened 2023-05-30 10:53 UTC by Oswaldo-Chan

ya avance la seccion 32 y me falta un video para terminarla

2023-05-31 00:42 UTC, CheloChidoone requested changes
Buen avance @Oswaldo-Chan, pero aquí es necesario que agregues un .gitignore donde ignores la carpeta de vendor porque esa no es necesario que la subas, así como cuando viste el tema de los node_modules ignorabas la carpeta y nosotros podíamos hacer npm install en este caso es lo mismo, puedes ignorar la carpeta y nosotros podemos hacer composer install igual que tu. Agrega tu .gitignore y borra la carpeta Vendor de tu repositorio para aprobar tu PR porfavor.

2023-05-31 10:54 UTC, Oswaldo-Chan commented
Hola, ya repare el error que me comentaste agregando el gitignore y de paso subo mi avance del dia 30 de mayo

2023-05-31 23:41 UTC, CheloChidoone requested changes
@Oswaldo-Chan, Gracias por las correcciones pero ahora con tu nuevo avance no puedo acceder a la parte de admin de tu proyecto ni al login.php porque agregaste que se revisara si habia iniciado sesion en el login.php y si no he iniciado me redireccionas al inicio pero eso no tiene sentido porque estoy llendo al login para iniciar sesion entonces ahi no debes redireccionar porque no puedo iniciar sesion, revisa eso por favor

2023-06-01 01:00 UTC, Oswaldo-Chan commented
Hola, ya reparé el error que me comentaste, se me olvidó cambiar los demás archivos y el archivo login.php no necesitaba la funcion userAuth()

2023-06-01 01:17 UTC, CheloChidoone approved these changes

2023-06-01 03:03 UTC, merged